### ISSUE TITLE
作者似乎没有上传环境配置文件，是否可以上传，非常感谢

### ISSUE THREAD

**Issue by zhengzheng-yay** [liuxiaohui1221/syntactic-experts#1]

**Comment by liuxiaohui1221** [comment]
gitee上有，https://gitee.com/niuxiangfly/syntactic-experts.git



xiao_辉
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "liuxiaohui1221/syntactic-experts"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月12日(星期一) 下午5:02
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[liuxiaohui1221/syntactic-experts] 作者似乎没有上传环境配置文件，是否可以上传，非常感谢 (Issue #1)
